/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swingexamples;

import java.awt.event.ActionEvent;
import java.util.*;

/**
 *
 * @author Bartlomiej_Kedziora
 */
public class Calculator extends javax.swing.JFrame {

  private String action;
  private String result;
  private Boolean firstClick;
  private String n1;
  private String n2;
  /**
   * Creates new form Calculator
   */
  public Calculator() {
    initComponents();
    invoke();
  }
  
  private void invoke() {
    result = "0";
    jLabel1.setText(result);
    action = "";
    n1 = "0";
    n2 = "";
    firstClick = true;
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jPanel3 = new javax.swing.JPanel();
    jButton1 = new javax.swing.JButton();
    jButton2 = new javax.swing.JButton();
    jButton3 = new javax.swing.JButton();
    jButton4 = new javax.swing.JButton();
    jButton5 = new javax.swing.JButton();
    jButton6 = new javax.swing.JButton();
    jButton7 = new javax.swing.JButton();
    jButton8 = new javax.swing.JButton();
    jButton9 = new javax.swing.JButton();
    jButton10 = new javax.swing.JButton();
    jButton11 = new javax.swing.JButton();
    jButton12 = new javax.swing.JButton();
    jButton13 = new javax.swing.JButton();
    jButton14 = new javax.swing.JButton();
    jButton15 = new javax.swing.JButton();
    jButton16 = new javax.swing.JButton();
    jButton17 = new javax.swing.JButton();
    jButton18 = new javax.swing.JButton();
    jButton19 = new javax.swing.JButton();
    jButton20 = new javax.swing.JButton();
    jButton21 = new javax.swing.JButton();
    jButton22 = new javax.swing.JButton();
    jButton23 = new javax.swing.JButton();
    jButton24 = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Kalkulator");

    jLabel1.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    jLabel1.setText("0");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, Short.MAX_VALUE))
    );

    jPanel3.setLayout(new java.awt.GridLayout(6, 4));

    jButton1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
    jButton1.setText("%");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });
    jPanel3.add(jButton1);

    jButton2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
    jButton2.setText("-");
    jPanel3.add(jButton2);

    jButton3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
    jButton3.setText("--");
    jPanel3.add(jButton3);

    jButton4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
    jButton4.setText("---");
    jPanel3.add(jButton4);

    jButton5.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
    jButton5.setText("CE");
    jPanel3.add(jButton5);

    jButton6.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
    jButton6.setText("C");
    jButton6.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton6ActionPerformed(evt);
      }
    });
    jPanel3.add(jButton6);

    jButton7.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
    jButton7.setText("<-");
    jPanel3.add(jButton7);

    jButton8.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
    jButton8.setText("/");
    jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jButton8MouseClicked(evt);
      }
    });
    jPanel3.add(jButton8);

    jButton9.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
    jButton9.setText("7");
    jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jButton9MouseClicked(evt);
      }
    });
    jPanel3.add(jButton9);

    jButton10.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
    jButton10.setText("8");
    jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jButton10MouseClicked(evt);
      }
    });
    jPanel3.add(jButton10);

    jButton11.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
    jButton11.setText("9");
    jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jButton11MouseClicked(evt);
      }
    });
    jPanel3.add(jButton11);

    jButton12.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
    jButton12.setText("X");
    jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jButton12MouseClicked(evt);
      }
    });
    jPanel3.add(jButton12);

    jButton13.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
    jButton13.setText("4");
    jButton13.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jButton13MouseClicked(evt);
      }
    });
    jPanel3.add(jButton13);

    jButton14.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
    jButton14.setText("5");
    jButton14.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jButton14MouseClicked(evt);
      }
    });
    jPanel3.add(jButton14);

    jButton15.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
    jButton15.setText("6");
    jButton15.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jButton15MouseClicked(evt);
      }
    });
    jPanel3.add(jButton15);

    jButton16.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
    jButton16.setText("-");
    jButton16.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jButton16MouseClicked(evt);
      }
    });
    jPanel3.add(jButton16);

    jButton17.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
    jButton17.setText("1");
    jButton17.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jButton17MouseClicked(evt);
      }
    });
    jPanel3.add(jButton17);

    jButton18.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
    jButton18.setText("2");
    jButton18.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jButton18MouseClicked(evt);
      }
    });
    jPanel3.add(jButton18);

    jButton19.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
    jButton19.setText("3");
    jButton19.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jButton19MouseClicked(evt);
      }
    });
    jPanel3.add(jButton19);

    jButton20.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
    jButton20.setText("+");
    jButton20.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton20ActionPerformed(evt);
      }
    });
    jPanel3.add(jButton20);

    jButton21.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
    jButton21.setText("+/-");
    jPanel3.add(jButton21);

    jButton22.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
    jButton22.setText("0");
    jButton22.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jButton22MouseClicked(evt);
      }
    });
    jPanel3.add(jButton22);

    jButton23.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
    jButton23.setText(",");
    jPanel3.add(jButton23);

    jButton24.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
    jButton24.setText("=");
    jButton24.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jButton24MouseClicked(evt);
      }
    });
    jPanel3.add(jButton24);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(24, 24, 24)
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jButton1ActionPerformed
  //0 button
  private void jButton22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton22MouseClicked
    buttonNumber("0");
    System.out.println("OK");
  }//GEN-LAST:event_jButton22MouseClicked
  //1 button
  private void jButton17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton17MouseClicked
    buttonNumber("1");
  }//GEN-LAST:event_jButton17MouseClicked
  //2 button
  private void jButton18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton18MouseClicked
    buttonNumber("2");
  }//GEN-LAST:event_jButton18MouseClicked
  //3 button
  private void jButton19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton19MouseClicked
    buttonNumber("3");
  }//GEN-LAST:event_jButton19MouseClicked
  //4 button
  private void jButton13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton13MouseClicked
    buttonNumber("4");
  }//GEN-LAST:event_jButton13MouseClicked
  //5 button
  private void jButton14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton14MouseClicked
    buttonNumber("5");
  }//GEN-LAST:event_jButton14MouseClicked
  //6 button
  private void jButton15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton15MouseClicked
    buttonNumber("6");
  }//GEN-LAST:event_jButton15MouseClicked
  //7 button
  private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
    buttonNumber("7");
  }//GEN-LAST:event_jButton9MouseClicked
  //8 button
  private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
    buttonNumber("8");
  }//GEN-LAST:event_jButton10MouseClicked
  //9 button
  private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
    buttonNumber("9");
  }//GEN-LAST:event_jButton11MouseClicked

// C button
  private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
    invoke();
  }//GEN-LAST:event_jButton6ActionPerformed
  //+ button
  private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
    if(n2.equals("")){
      action="a";
      firstClick = true;
    }
    else {
      result();
      action="a";
    }
  }//GEN-LAST:event_jButton20ActionPerformed
  //= button
  private void jButton24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton24MouseClicked
    result();
  }//GEN-LAST:event_jButton24MouseClicked
  //- button
  private void jButton16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton16MouseClicked
    if(n2.equals("")){
      action="s";
      firstClick = true;
      //firstClick = true;
    }
    else {
      result();
      action="s";
    }
  }//GEN-LAST:event_jButton16MouseClicked
  //x button
  private void jButton12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseClicked
    if(n2.equals("")){
      action="m";
      firstClick = true;
    }
    else {
      result();
      action="m";
    }
  }//GEN-LAST:event_jButton12MouseClicked
  /// button
  private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
    if(n2.equals("0")){
      jLabel1.setText("You can't divide by zero!");
      throw new EmptyStackException();
    }
    else if(n2.equals("")){
      action="d";
      firstClick = true;
    }
    else {
      result();
      action="d";
    }
  }//GEN-LAST:event_jButton8MouseClicked
  
  private void buttonNumber(String no){
    String getContentJLabel1 = jLabel1.getText();
    if(getContentJLabel1.equals("0")) {
      getContentJLabel1 = "";
    }
    if(firstClick) {
      jLabel1.setText(no);
      firstClick = false;
    }
    else {
      jLabel1.setText(getContentJLabel1 + no);
    }
    if(action.equals("")){
      n1 = jLabel1.getText();
    }
    else {
      n2 = jLabel1.getText();
    }
  }
  
  private void result(){
    double check = action(Double.parseDouble(n1), Double.parseDouble(n2));
    if(check % 1 == 0) {
      result = String.valueOf((int)check);
    }
    else {
      result = String.valueOf(check);
    }
    System.out.println(n1 +":"+ n2+" action="+ action + " result: "+ result);
    jLabel1.setText(result);
    n1 = result;
    n2 = "";
    action = "";
    firstClick = true;
  }
  
  private double action(double x, double y) {
    double out;
    out=0;
    switch(action) {
      case "a":
        out = x+y;
        break;
      case "s":
        out = x-y;
        break;
      case "m":
        out = x*y;
        break;
      case "d":
        out = x/y;
        break;
      default:
        break;
    }
    return out;
  }
  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new Calculator().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton10;
  private javax.swing.JButton jButton11;
  private javax.swing.JButton jButton12;
  private javax.swing.JButton jButton13;
  private javax.swing.JButton jButton14;
  private javax.swing.JButton jButton15;
  private javax.swing.JButton jButton16;
  private javax.swing.JButton jButton17;
  private javax.swing.JButton jButton18;
  private javax.swing.JButton jButton19;
  private javax.swing.JButton jButton2;
  private javax.swing.JButton jButton20;
  private javax.swing.JButton jButton21;
  private javax.swing.JButton jButton22;
  private javax.swing.JButton jButton23;
  private javax.swing.JButton jButton24;
  private javax.swing.JButton jButton3;
  private javax.swing.JButton jButton4;
  private javax.swing.JButton jButton5;
  private javax.swing.JButton jButton6;
  private javax.swing.JButton jButton7;
  private javax.swing.JButton jButton8;
  private javax.swing.JButton jButton9;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel3;
  // End of variables declaration//GEN-END:variables
}
